<a href="https://colab.research.google.com/github/Paladin-88/data-science/blob/main/%D0%A4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B9_%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Отчет составил: Наумов Михаил Андреевич

In [ ]:
import numpy as np # линейная алгебра
import pandas as pd # обработка данных
import matplotlib.pyplot as plt
import factor_analyzer

In [ ]:
data = pd.read_csv('D:\_6c939ae474f29a209ab5e3901864d38a_Data_Projects.csv', sep=';', decimal=',') # считываем датасет
data.head(10) # выводим первые 10 значенией

AddressCount  CallsCount  ClicksCount  FirmsCount   GeoPart  MobilePart  \
0           156          20         1903         176  0.416104    0.535762   
1            17          37          258          20  0.211679    0.430657   
2            78          56         1956         185  0.349475    0.476594   
3            14          70          378          19  0.318718    0.463744   
4           111          90         4089          90  0.556175    0.490573   
5            53          96         1669         162  0.398978    0.421737   
6            18         137          373          26  0.407108    0.389338   
7             9         150          563          15  0.187886    0.175525   
8            56         153         1366          56  0.335469    0.498856   
9           371         176         5913          31  0.288146    0.608774   

   UsersCount     Distance  IsGeo  
0        1125   749.966084      1  
1         157  2289.032424      0  
2        1195  1423.376512      1  
3         206  3396.566089      0  
4        2934  1576.514154      1  
5         991  2337.603777      0  
6         180  2780.961789      0  
7         265  5206.838454      0  
8         613  2704.490401      0  
9        3981  4333.989691      0

In [ ]:
# Переводим стороковые значения в числовые 
pd.to_numeric(data['AddressCount'])
pd.to_numeric(data['CallsCount'])
pd.to_numeric(data['ClicksCount'])
pd.to_numeric(data['FirmsCount'])
pd.to_numeric(data['MobilePart'])
pd.to_numeric(data['UsersCount'])
pd.to_numeric(data['Distance'])
pd.to_numeric(data["GeoPart"])

0     0.416104
1     0.211679
2     0.349475
3     0.318718
4     0.556175
        ...   
74    0.364710
75    0.415795
76    0.308071
77    0.427646
78    0.431926
Name: GeoPart, Length: 79, dtype: float64

In [ ]:
data.head(20) # выводим первые 20 значенией

AddressCount  CallsCount  ClicksCount  FirmsCount   GeoPart  MobilePart  \
0            156          20         1903         176  0.416104    0.535762   
1             17          37          258          20  0.211679    0.430657   
2             78          56         1956         185  0.349475    0.476594   
3             14          70          378          19  0.318718    0.463744   
4            111          90         4089          90  0.556175    0.490573   
5             53          96         1669         162  0.398978    0.421737   
6             18         137          373          26  0.407108    0.389338   
7              9         150          563          15  0.187886    0.175525   
8             56         153         1366          56  0.335469    0.498856   
9            371         176         5913          31  0.288146    0.608774   
10          9552         207       101558        1473  0.383507    0.705315   
11            42         222         1154          64  0.223269    0.139612   
12            84         228         1031          39  0.310968    0.237456   
13            48         237         1307          14  0.203375    0.669183   
14            30         256         1139         114  0.318486    0.231626   
15            70         270          976         132  0.246795    0.133974   
16            73         278         2805          42  0.322342    0.440951   
17           258         310         3970         245  0.313795    0.458652   
18            61         319         1316         168  0.367380    0.343316   
19            66         344         1478          35  0.092917    0.090000   

    UsersCount     Distance  IsGeo  
0         1125   749.966084      1  
1          157  2289.032424      0  
2         1195  1423.376512      1  
3          206  3396.566089      0  
4         2934  1576.514154      1  
5          991  2337.603777      0  
6          180  2780.961789      0  
7          265  5206.838454      0  
8          613  2704.490401      0  
9         3981  4333.989691      0  
10       54098   813.439315      1  
11         410  4511.632303      0  
12         578  6272.751840      0  
13         596  3969.150362      1  
14         550  4149.002902      0  
15         537  4522.585897      0  
16        1196  2775.018152      0  
17        2344   893.981377      1  
18         558  1033.112765      0  
19         500  5528.065546      0

In [ ]:
data.info() # получаем информацию о датасете и его значениях

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   AddressCount  79 non-null     int64  
 1   CallsCount    79 non-null     int64  
 2   ClicksCount   79 non-null     int64  
 3   FirmsCount    79 non-null     int64  
 4   GeoPart       79 non-null     float64
 5   MobilePart    79 non-null     float64
 6   UsersCount    79 non-null     int64  
 7   Distance      79 non-null     float64
 8   IsGeo         79 non-null     int64  
dtypes: float64(3), int64(6)
memory usage: 5.7 KB


In [ ]:
data.describe() # выволим информацию о основных статических показателях датасета

AddressCount    CallsCount    ClicksCount   FirmsCount    GeoPart  \
count     79.000000     79.000000      79.000000    79.000000  79.000000   
mean    1048.037975   3648.683544   21826.012658   305.088608   0.342645   
std     1642.066119   8124.105402   32474.959513   382.052090   0.103608   
min        9.000000     20.000000     258.000000    14.000000   0.092917   
25%       81.000000    346.000000    2055.000000    71.500000   0.281527   
50%      371.000000    931.000000    6921.000000   185.000000   0.322342   
75%     1195.000000   2457.500000   30625.500000   402.500000   0.416907   
max     9552.000000  48497.000000  167155.000000  2379.000000   0.556175   

       MobilePart    UsersCount     Distance      IsGeo  
count   79.000000     79.000000    79.000000  79.000000  
mean     0.445746   9753.126582  2669.426352   0.354430  
std      0.146131  13927.295721  1427.785304   0.481397  
min      0.090000    157.000000   714.787236   0.000000  
25%      0.357293   1167.500000  1562.103740   0.000000  
50%      0.463744   2934.000000  2586.503274   0.000000  
75%      0.551654  13265.000000  3575.692331   1.000000  
max      0.737288  61127.000000  6292.207311   1.000000

In [ ]:
df = pd.DataFrame(data, columns=['UsersCount', 'Distance'])
df = df.astype(int)

In [ ]:
df.head()

UsersCount  Distance
0        1125       749
1         157      2289
2        1195      1423
3         206      3396
4        2934      1576

# Факторный анализ

Для аналиаза был выбран метод факторного анализа. 
Факторный анализ - это метод сокращения данных. Он исследует базовую структуру наблюдаемых данных, изучая внутренние зависимости между многими переменными, и использует несколько гипотетических переменных для представления своей основной структуры данных. Эти несколько гипотетических переменных могут отражать основную информацию о многих исходных переменных. Исходные переменные - это наблюдаемые и очевидные переменные, а гипотетические переменные - это ненаблюдаемые скрытые переменные, называемые факторами.

Например, при осуществлении нашего анализа будет использоваться фактор геозависимости. 

Тест Бартлетта проверяет, коррелируют ли наблюдаемые переменные вообще, используя наблюдаемую корреляционную матрицу с единичной матрицей. Если тест оказался статистически незначимым, не следует использовать факторный анализ/

In [ ]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value,p_value=calculate_bartlett_sphericity(df)
chi_square_value, p_value

(14.148980567089612, 0.0001688885951293418)

В этом тесте Бартлетта p-значение практически равна 0. Тест был статистически значимым, что указывало на то, что наблюдаемая корреляционная матрица не является тождественной матрицей.

Тест Кайзера-Мейера-Олкина (КМО) измеряет пригодность данных для факторного анализа. Он определяет адекватность для каждой наблюдаемой переменной и для всей модели. KMO оценивает долю дисперсии среди всех наблюдаемых переменных. Идентификатор более низкой доли больше подходит для факторного анализа. Значения KMO находятся в диапазоне от 0 до 1. Значение KMO менее 0,5 считается недостаточным.

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all,kmo_model=calculate_kmo(df)
kmo_model

0.49363083164300225

Итоговый  KMO для наших данных находится у пограничного значения в 0,5, что является средним показателем. Однако, данный показатель позволяет нам продолжить запланированный факторный анализ.

### Выбор количества факторов

 Для выбора количества факторов можно использовать критерий Кайзера и график осыпи. Оба основаны на собственных значениях.

In [ ]:
from factor_analyzer import FactorAnalyzer
# Проверка значений
fa = FactorAnalyzer(10, rotation=None)
fa.fit(df)
# Check Eigenvalues
ev, v = fa.get_eigenvalues()
ev

array([1.38393948, 0.61606052])

Здесь вы можете видеть только один фактор собственные значения больше единицы. Это означает, что нам нужно выбрать только 1 фактор.

In [ ]:
fa.get_factor_variance()

(array([7.67878956e-01, 2.65443273e-09]),
 array([3.83939478e-01, 1.32721636e-09]),
 array([0.38393948, 0.38393948]))

In [ ]:
Итоговая 38% кумулятивная дисперсия, объясняемая 1 фактором.

 ## Вывод:

Факторный анализ исследует большой набор данных и находит взаимосвязанные признаки. Он  идентифицирует группы взаимосвязанных переменных, которые помогают исследователям рынка сжимать рыночные ситуации и находить скрытые взаимосвязи между потребительскими вкусами, предпочтениями и территориальной расположенностью. Результаты факторного анализа могут быть противоречивы. Его интерпретации могут быть спорными, потому что для одних и тех же факторов данных можно сделать более одной интерпретации. После идентификации факторов и именования факторов требуется знание предметной области.


# Отчет составил: Наумов Михаил Андреевич